steps:
- name: "echo from bash"
  script: |
    #!/usr/bin/env bash
    echo "Hello World from bash"

- name: "Shell example"
  shell: echo "Shell is working"

- name: "echo from python"
  script: |
    #!/usr/bin/env python
    print('hello from python')

- name: "setup variable via env"
  env:
  - 'prj_id=$PROJECT_ID'
  script: 'echo $prj_id'

- name: "setup variable via bash"
  script: |
    #!/usr/bin/bash
    prj_id=hari_gcptech
    echo 'My project ID is: $prj_id'
